name: Integration Test Suite (Mezmo)

on:
  workflow_dispatch:
  push:
    branches:
      - master

concurrency:
  # For pull requests, cancel running workflows, for master, run all
  #
  # `github.event.number` exists for pull requests, otherwise fall back to SHA
  # for master
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

env:
  AUTOINSTALL: true
  AWS_ACCESS_KEY_ID: "dummy"
  AWS_SECRET_ACCESS_KEY: "dummy"
  CONTAINER_TOOL: "docker"
  RUST_BACKTRACE: full
  RUST_TEST_THREADS: 1
  TEST_LOG: vector=debug
  VERBOSE: true
  CI: true
  PROFILE: debug

jobs:
  test-integration:
    name: Integration - Linux, ${{ matrix.test }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          # Integrations that we are not using/supporting are disabled
          - test: 'aws'
          # - test: 'azure'
          # - test: 'clickhouse'
          # - test: 'datadog-agent'
          # - test: 'datadog-logs'
          # - test: 'datadog-metrics'
          # - test: 'datadog-traces'
          # - test: 'dnstap'
          # - test: 'docker-logs'
          - test: 'elasticsearch'
          # - test: 'eventstoredb'
          - test: 'fluent'
          - test: 'gcp'
          # - test: 'humio'
          # - test: 'influxdb'
          - test: 'kafka'
          - test: 'logstash'
          # - test: 'loki'
          # - test: 'mongodb'
          # - test: 'nats'
          # - test: 'nginx'
          # - test: 'postgres'
          # - test: 'prometheus'
          # - test: 'pulsar'
          # - test: 'redis'
          # - test: 'shutdown'
          - test: 'splunk'
          - test: 'postgres'
            env:
              SPLUNK_VERSION: 7.3.9
          - test: 'splunk'
    steps:
      - uses: actions/checkout@v3
      - run: make ci-sweep
      - run: make test-integration-${{ matrix.test }}
        env:
          SPLUNK_VERSION: ${{ matrix.env.SPLUNK_VERSION }}
      - run: make test-integration-${{ matrix.test }}-cleanup
        if: ${{ always() }}

  test-integration-check:
    name: test-integration-check
    runs-on: ubuntu-20.04
    needs:
      - test-integration
    steps:
      - name: validate
        run: echo "OK"
